config/routes.rb
CoolGames::Engine.routes.draw do
  resources :games do
    member do
      get *%w(play resign undo_guess_moves next do_this mark_dead messages)
      post *%w(send_message)
    end

    collection do
      get *%w(waiting)
    end
  end

  resources :uploads
  match "upload_search" => "upload_search#index"

  resources :players do
    collection do
      get *%w(search suggest suggest_opponents)
    end
  end

  resources :pairs

  resources :invitations do
    member do
      get *%w(accept reject cancel)
    end
  end
end

app/models/cool_games/abstract_player_stat.rb
module CoolGames
  module AbstractPlayerStat
    def games
      games_as_black + games_as_white
    end

    def games_won
      games_won_as_black + games_won_as_white
    end

    def games_lost
      games_lost_as_black + games_lost_as_white
    end
  end
end

app/models/cool_games/board.rb
module CoolGames
  class Board < Array
    attr :game_type

    CHARS = "0123456789:"

    NONE            = 0
    BLACK           = 1
    WHITE           = 2
    BLACK_DEAD      = 3
    WHITE_DEAD      = 4
    BLACK_TERRITORY = 5
    WHITE_TERRITORY = 6
    SHARED          = 9
    DAME            = 10 # dan guan
    VISITED         = 99

    def initialize size, game_type = Game::WEIQI
      @size      = size
      @game_type = game_type
      reset
    end

    def daoqi?
      @game_type == Game::DAOQI
    end

    def clone
      b = Board.new size, game_type
      0.upto(size - 1) do |x|
        0.upto(size - 1) do |y|
          b[x][y] = self[x][y]
        end
      end
      b
    end

    def inspect
      "\n" + map(&:inspect).join("\n")
    end

    def neighbor? x1, y1, x2, y2
      if daoqi?
        if x1 == x2
          y1 == (y2+1) % @size or y1 == (y2-1+@size) % @size
        elsif y1 == y2
          x1 == (x2+1) % @size or x1 == (x2-1+@size) % @size
        end
      else
        if x1 == x2
          y1 == y2 + 1 or y1 == y2 - 1
        elsif y1 == y2
          x1 == x2 + 1 or x1 == x2 - 1
        end
      end
    end

    def occupied? x, y
      self[x][y] != 0
    end

    def normalize index
      raise 'normalize() is only applicable to DAOQI' if @game_type == Game::WEIQI

      if index < 0
        index + @size
      elsif index >= @size
        index - @size
      else
        index
      end
    end

    def reset
      for i in 0..@size - 1 do
        self[i] = Array.new @size
        for j in 0..@size - 1 do
          self[i][j] = 0
        end
      end
    end

    def play color, x, y
      return [] if color == 0

      self[x][y] = color

      dead = []
      remove_group = lambda do |group|
        if group
          group.each do |x, y|
            dead << [x, y]
            self[x][y] = 0
          end
        end
      end

      opponent_color = color == BLACK ? WHITE : BLACK

      remove_group.call get_dead_group(x-1, y) if (@game_type == Game::DAOQI or x > 0        ) and self[x-1][y] == opponent_color
      remove_group.call get_dead_group(x+1, y) if (@game_type == Game::DAOQI or x < @size - 1) and self[x+1][y] == opponent_color
      remove_group.call get_dead_group(x, y-1) if (@game_type == Game::DAOQI or y > 0        ) and self[x][y-1] == opponent_color
      remove_group.call get_dead_group(x, y+1) if (@game_type == Game::DAOQI or y < @size - 1) and self[x][y+1] == opponent_color

      remove_group.call get_dead_group(x, y)

      dead
    end

    def count whose_turn
      mark_territories
      finish_dame whose_turn

      b = w = 0
      for i in 0..@size - 1
        for j in 0..@size - 1
          case self[i][j]
            when BLACK, BLACK_TERRITORY, WHITE_DEAD
              b += 1
            when WHITE, WHITE_TERRITORY, BLACK_DEAD
              w += 1
            when SHARED
              b += 0.5
              w += 0.5
          end
        end
      end

      return b, w
    end

    def get_dead_group x, y
      if daoqi?
        x = normalize(x)
        y = normalize(y)
      else
        return if x < 0 or x>=@size or y<0 or y>= @size
      end

      return if self[x][y] == 0

      if @game_type == Game::DAOQI
        return if self[normalize(x-1)][y] == 0 or
                  self[normalize(x+1)][y] == 0 or
                  self[x][normalize(y-1)] == 0 or
                  self[x][normalize(y+1)] == 0
      else
        return if (x > 0       and self[x-1][y] == 0) or
                  (x < @size-1 and self[x+1][y] == 0) or
                  (y > 0       and self[x][y-1] == 0) or
                  (y < @size-1 and self[x][y+1] == 0)
      end

      group = PointGroup.new(self[x][y])
      group << [x,y]

      return if ((daoqi? or x > 0      ) and expand_dead_group(group, x-1, y)) or
                ((daoqi? or x < @size-1) and expand_dead_group(group, x+1, y)) or
                ((daoqi? or y > 0      ) and expand_dead_group(group, x, y-1)) or
                ((daoqi? or y < @size-1) and expand_dead_group(group, x, y+1))

      group
    end

    def get_dead_group_for_marking x, y
      if daoqi?
        x = normalize(x)
        y = normalize(y)
      else
        return if x < 0 or x>=@size or y<0 or y>= @size
      end

      return if self[x][y] == 0

      group = PointGroup.new(self[x][y])
      group << [x,y]

      expand_dead_group_for_marking(group, x-1, y) if daoqi? or x > 0
      expand_dead_group_for_marking(group, x+1, y) if daoqi? or x < @size-1
      expand_dead_group_for_marking(group, x, y-1) if daoqi? or y > 0
      expand_dead_group_for_marking(group, x, y+1) if daoqi? or y < @size-1

      group.reject! {|point| self[point[0]][point[1]] == 0}
      group
    end

    def mark_dead_group group
      group.each do |x, y|
        if self[x][y] == 1
          self[x][y] = BLACK_DEAD
        elsif self[x][y] == 2
          self[x][y] = WHITE_DEAD
        end
      end
    end

    def mark_territories
      for i in 0..@size - 1
        for j in 0..@size - 1
          if self[i][j] == 0
            @black_neighbor = @white_neighbor = false
            group = expand_blank_group i, j
            unless group.blank?
              if @black_neighbor and @white_neighbor
                group.each{|x, y| self[x][y] = DAME }
              elsif @black_neighbor
                group.each{|x, y| self[x][y] = BLACK_TERRITORY }
              elsif @white_neighbor
                group.each{|x, y| self[x][y] = WHITE_TERRITORY }
              else
                group.each{|x, y| self[x][y] = DAME }
              end
            end
          end
        end
      end
    end

    def finish_dame whose_turn
      for i in 0..@size - 1
        for j in 0..@size - 1
          if self[i][j] == DAME
            if whose_turn == 1
              self[i][j] = BLACK_TERRITORY
              whose_turn = 2
            else
              self[i][j] = WHITE_TERRITORY
              whose_turn = 1
            end
          end
        end
      end
    end

    def points_str
      @points_str = "0" * size * size
      0.upto(size-1) do |x|
        0.upto(size-1) do |y|
          @points_str[x*size + y] = CHARS[self[x][y], 1]
        end
      end
      @points_str
    end

    def dump
      {
        'size' => size,
        'game_type' => game_type,
        'points' => points_str
      }.to_json
    end

    def self.load input
      hash = JSON.load input
      b = Board.new hash['size'], hash['game_type']
      s = hash['points']
      start_char_code = 48 # '0'
      0.upto(s.length - 1) do |i|
        x = i/b.size
        y = i%b.size
        b[x][y] = s[i].ord - start_char_code # TODO: String#ord works in Ruby 1.9 only
      end
      b
    end

    private

    def expand_dead_group group, x, y
      if daoqi?
        x = normalize(x)
        y = normalize(y)
      end

      return if group.include?([x, y]) # already added to the group
      return if self[x][y] != group.color

      if daoqi?
        return true if self[normalize(x-1)][y] == 0 or
                       self[normalize(x+1)][y] == 0 or
                       self[x][normalize(y-1)] == 0 or
                       self[x][normalize(y+1)] == 0
      else
        return true if (x > 0       and self[x-1][y] == 0) or
                       (x < @size-1 and self[x+1][y] == 0) or
                       (y > 0       and self[x][y-1] == 0) or
                       (y < @size-1 and self[x][y+1] == 0)
      end

      group << [x,y]

      ((daoqi? or x > 0      ) and expand_dead_group(group, x-1, y)) or
      ((daoqi? or x < @size-1) and expand_dead_group(group, x+1, y)) or
      ((daoqi? or y > 0      ) and expand_dead_group(group, x, y-1)) or
      ((daoqi? or y < @size-1) and expand_dead_group(group, x, y+1))
    end

    def expand_dead_group_for_marking group, x, y
      if daoqi?
        x = normalize(x)
        y = normalize(y)
      end

      return if group.include?([x, y]) # already added to the group

      opponent_color = group.color == 1 ? 2 : 1
      return if self[x][y] == opponent_color

      group << [x,y]

      expand_dead_group_for_marking(group, x-1, y) if daoqi? or x > 0
      expand_dead_group_for_marking(group, x+1, y) if daoqi? or x < @size-1
      expand_dead_group_for_marking(group, x, y-1) if daoqi? or y > 0
      expand_dead_group_for_marking(group, x, y+1) if daoqi? or y < @size-1
    end

    def expand_blank_group x, y, group = nil
      if daoqi?
        x = normalize(x)
        y = normalize(y)
      end

      case self[x][y]
      when 0
        group ||= []
        group << [x, y]
        self[x][y] = VISITED
        expand_blank_group(x-1,y,group) if daoqi? or x > 0
        expand_blank_group(x+1,y,group) if daoqi? or x < @size-1
        expand_blank_group(x,y-1,group) if daoqi? or y > 0
        expand_blank_group(x,y+1,group) if daoqi? or y < @size-1
      when 1, WHITE_DEAD
        @black_neighbor = true
      when 2, BLACK_DEAD
        @white_neighbor = true
      end

      group
    end
  end
end

app/models/cool_games/game_detail.rb
module CoolGames
  class GameDetail < ActiveRecord::Base

    set_table_name "cg_game_details"

    belongs_to :game
    belongs_to :first_move, :class_name => 'GameMove', :foreign_key => 'first_move_id'
    belongs_to :last_move,  :class_name => 'GameMove', :foreign_key => 'last_move_id'

    has_many :all_moves, :class_name => 'GameMove', :dependent => :destroy

    after_create do
      move = GameMove.create!(:game_detail_id => id,
                              :move_no => 0, :x => -1, :y => -1, :color => 0, :played_at => Time.now,
                              :setup_points => handicaps)
      self.formatted_moves = ::CoolGames::Sgf::NodeRenderer.new(:with_name => true).render(move)
      self.first_move_id = self.last_move_id = move.id
      self.last_move_time = Time.now
      save!
    end

    def change_turn
      if whose_turn == Game::WHITE
        self.whose_turn = Game::BLACK
      else
        self.whose_turn = Game::WHITE
      end
    end

    def guess_moves
      last_move.children
    end

    private

    def handicaps
      points = []
      case game.handicap
        when 2 then points << [3, 3] << [15, 15]
        when 3 then points << [3, 3] << [15, 15] << [3, 15]
        when 4 then points << [3, 3] << [15, 15] << [3, 15] << [15, 3]
        when 5 then points << [3, 3] << [15, 15] << [3, 15] << [15, 3] << [9, 9]
        when 6 then points << [3, 3] << [15, 15] << [3, 15] << [15, 3] << [3, 9] << [15, 9]
        when 7 then points << [3, 3] << [15, 15] << [3, 15] << [15, 3] << [3, 9] << [15, 9] << [9, 9]
        when 8 then points << [3, 3] << [15, 15] << [3, 15] << [15, 3] << [3, 9] << [15, 9] << [9, 3] << [9, 15]
        when 9 then points << [3, 3] << [15, 15] << [3, 15] << [15, 3] << [3, 9] << [15, 9] << [9, 3] << [9, 15] << [9, 9]
      end
      points.map{|point| [Game::ADD_BLACK_STONE, point[0], point[1]]}.to_json
    end
  end
end

app/models/cool_games/game_move.rb
module CoolGames
  class GameMove < ActiveRecord::Base

    set_table_name "cg_game_moves"

    OCCUPIED = 1
    SUICIDE  = 2
    BAD_KO   = 3

    belongs_to :parent, :class_name => 'GameMove', :foreign_key => 'parent_id'
    belongs_to :game_detail

    serialize :dead

    scope :moves_after, lambda { |move|
      {:conditions => ["game_detail_id = ? and id > ?", move.game_detail_id, move.id]}
    }

    def move_on_board?
      color != Game::NONE
    end

    def children moves = nil
      return @children unless @children.nil?

      @children = []
      moves ||= self.class.moves_after(self)
      moves.each do |move|
        if move.parent_id == id
          @children << move
          moves.delete_at moves.index(move)
        end
      end

      @children.each do |move|
        move.children moves
      end

      @children
    end

    def board
      return @board if @board
      return @board = Board.load(serialized_board) if serialized_board

      init_board
    end

    def process
      return OCCUPIED if parent and parent.board.occupied?(x, y)

      init_board

      return SUICIDE if suicide?
      return BAD_KO if check_ko

      self.serialized_board = board.dump
    end

    def child_that_matches x, y
      children.detect {|move| move.x == x and move.y == y }
    end

    private

    def init_board
      if parent
        @board = parent.board.clone
      else
        @board = Board.new(game_detail.game.board_size, game_detail.game.game_type)
      end

      self.dead = @board.play(color, x, y)

      @board
    end

    def check_ko
      return if dead.blank? or dead.size != 1
      return unless parent
      return if parent.dead.blank? or parent.dead.size != 1

      dead_x, dead_y = *dead[0]
      old_dead_x, old_dead_y = *parent.dead[0]

      dead_x == parent.x and dead_y == parent.y and old_dead_x == x and old_dead_y == y
    end

    def suicide?
      dead.include?([x, y])
    end
  end
end

app/models/cool_games/gaming_platform.rb
# coding: utf-8
module CoolGames
  class GamingPlatform < ActiveRecord::Base

    set_table_name "cg_gaming_platforms"

    ALL = 999

    default_scope :order => 'name'

    def self.kgs
      @kgs ||= self.find_by_name('KGS')
    end

    def self.dgs
      @dgs ||= self.find_by_name('DGS')
    end

    def self.tom
      @tom ||= self.find_by_name('TOM')
    end

    def self.igs
      @igs ||= self.find_by_name('IGS')
    end

    def self.sina
      @sina ||= self.find_by_name('Sina')
    end

    def self.eweiqi
      @eweiqi ||= self.find_by_name('eWeiqi')
    end

    def self.gocool
      @gocool ||= self.find_by_name('Gocool')
    end

    def link_html
      url = self.url
      url = "http://" + url unless url =~ /html\:/
      "<a href='#{url}' target='_new'>#{name}</a>"
    end
  end
end

app/models/cool_games/message.rb
module CoolGames
  class Message < ActiveRecord::Base

    set_table_name "cg_messages"

    # Message Type
    REGULAR = 0
    PRIVATE = 1
    COMMENT = 2
    ADMIN   = 3
    OTHER   = 9

    # Source type
    SYSTEM = 0
    PLAYER = 1

    # Receiver type
    GAME   = 0
    PLAYER = 1

    # Level
    TRIVIAL   = 10
    INFO      = 20
    ATTENTION = 30
    IMPORTANT = 40

    scope :for_game, lambda {|game_id|
      {
        :conditions => ['receiver_id = ?', game_id]
      }
    }

    def initialize(attributes = {}, options = {})
      defaults = {:message_type => REGULAR, :source_type => SYSTEM, :source => "SYSTEM", :receiver_type => GAME, :level => INFO}
      super(defaults.merge(attributes), options)
    end

    def to_json *args
      created_at_str = created_at.strftime("%Y-%m-%d %H:%M")
      {:created_at_str => created_at_str}.merge(attributes).to_json
    end
  end
end

app/models/cool_games/nation_region.rb
module CoolGames
  class NationRegion < ActiveRecord::Base

    set_table_name "cg_nation_regions"

  end
end

app/models/cool_games/pair_stat.rb
module CoolGames
  class PairStat < ActiveRecord::Base
    include AbstractPlayerStat

    set_table_name "cg_pair_stats"

    belongs_to :player, :class_name => "Player", :foreign_key => :player_id
    belongs_to :opponent, :class_name => "Player", :foreign_key => :opponent_id

    default_scope :include => 'opponent'

    scope :opponent_name_like, lambda{ |name|
      { :conditions => ["name like ?", name] }
    }

    scope :sort_by_opponent_name, joins(:opponent).order(:name)

    def self.find_or_create player_id, opponent_id
      find_by_player_id_and_opponent_id(player_id, opponent_id) || create!(:player_id => player_id, :opponent_id => opponent_id)
    end
  end
end

app/models/cool_games/player_stat.rb
module CoolGames
  class PlayerStat < ActiveRecord::Base
    include AbstractPlayerStat

    set_table_name "cg_player_stats"
  end
end

app/models/cool_games/point_group.rb
module CoolGames
  class PointGroup < Array
    attr :color

    def initialize color
      @color = color
    end
  end
end

app/models/cool_games/point_on_board.rb
module CoolGames
  class PointOnBoard
    attr_reader :x, :y, :color, :move_no

    def initialize x, y, color, move_no, delete = nil
      @x        = x
      @y        = y
      @color    = color
      @move_no  = move_no
      @delete   = delete
    end

    def delete?
      @delete
    end
  end
end

app/models/cool_games/thread_globals.rb
module CoolGames
  module ThreadGlobals
    def logged_in?
      not current_user.nil?
    end

    def current_user
      Thread.current[:user]
    end

    def current_player
      current_user.nil_or.player
    end
  end
end

app/models/cool_games/upload_result.rb
module CoolGames
  class UploadResult
    SUCCESS           = 1
    FOUND             = 2
    VALIDATION_ERROR  = 3
    ERROR             = 4
    SGF_ERROR         = 5

    attr_accessor :upload, :status, :detail, :found_upload

    def initialize attrs = {}
      attrs.each do |key, value|
        method = :"#{key}="
        self.send(method, value) if self.respond_to? method
      end
    end
  end
end

app/views/cool_games/uploads/_upload_file_form.html.haml
= form_tag uploads_url, :name=>"upload_file_form", :id => "upload_file_form", :multipart => true, :class => "upload_game" do
  %fieldset
    .row
      .span4
        %label(for="upload_description")= t('uploads.description_label')
      .span8
        %input#upload_description(type="text" name="upload_description" size="80")
        %p= t('uploads.description_note')

    .row
      .span4
        %label(for="upload_upload")
          = t('uploads.file_label')
          =raw mark_required
          %br
          =raw t('uploads.file_note')
      .span8
        #file_fields
          %input#upload_upload(type="file" name="upload[upload]" size="60")
        %p=raw t('uploads.zip_file_note')

    .row.buttons
      .offset4
        %input(type='hidden' name='upload_type' value='file')
        %input.upload_submit{:type => "submit", :name => "commit", :value => t('uploads.submit_button')}
        %input#resetButton{:type => "reset", :value => t('form.reset_button')}

- content_for :footer do
  :javascript
    validanguage.el.upload_upload = {
      required: true,
      errorMsg: "#{t('uploads.file_required')}"
    };

app/views/cool_games/uploads/_upload_result.html.haml
%tr{:class => "record " + (upload_result_counter%2 == 0 ? "even-record":"")}
  %td= upload_result.upload.file_file_name
  %td= display_upload_status(upload_result)
  %td= display_upload_detail(upload_result)
  %td.actions
    - if upload_result.status == UploadResult::SUCCESS
      %a{:href => upload_url(upload_result.upload)}= t('form.view_button')
    - elsif upload_result.status == UploadResult::FOUND
      %a{:href => upload_url(upload_result.found_upload)}= t('form.view_button')

app/views/cool_games/uploads/_upload_results.html.haml
#update_results_container.active-scaffold.blue-theme
  %table#update_results_table
    %thead
      %tr.header
        %th#file_name_column= t('uploads.result.file_name')
        %th#upload_status_column= t('uploads.result.status')
        %th#upload_detail_column= t('uploads.result.detail')
        %th#actions_column &nbsp;
    %tbody.records
      = render :partial => 'upload_result', :collection => @upload_results

app/views/cool_games/uploads/_upload_sgf_form.html.haml
= form_tag uploads_url, :name => "upload_sgf_form", :id => "upload_sgf_form", :class => "upload_game" do
  %fieldset
    .row
      .span4
        %label(for="upload_description3")= t('uploads.description_label')
      .span8
        %input#upload_description3(type="text" name="upload_description" size="80")

    .row
      .span4
        %label(for='data')
          = t('uploads.data_label')
          =raw mark_required
      .span8
        %textarea#upload_data{:name => "upload[data]", :cols => 120, :rows => 20}

    .row
      .offset4
        %input(type='hidden' name='upload_type' value='sgf')
        %input.upload_submit{:type => "submit", :name => "commit", :value => t('uploads.submit_button')}
        %input{:type => "reset", :value => t('form.reset_button')}

- content_for :footer do
  :javascript
    validanguage.el.upload_data = {
      required: true,
      errorMsg: "#{t('uploads.data_required')}"
    };

app/views/cool_games/uploads/_upload_url_form.html.haml
= form_tag uploads_url, :name => "upload_url_form", :id => "upload_url_form", :class => "upload_game" do
  %fieldset
    .row
      .span4
        %label(for="upload_description2")= t('uploads.description_label')
      .span8
        %input#upload_description2(type="text" name="upload_description" size="80")

    .row
      .span4
        %label(for="upload_url")
          = t('uploads.url_label')
          =raw mark_required
      .span8
        %input#upload_url(type="text" name="upload[url]" size="80")

    .row
      .offset4
        %input(type='hidden' name='upload_type' value='url')
        %input.upload_submit{:type => "submit", :name => "commit", :value => t('uploads.submit_button')}
        %input{:type => "reset", :value => t('form.reset_button')}

- content_for :footer do
  :javascript
    validanguage.el.upload_url = {
      required: true,
      errorMsg: "#{t('uploads.url_required')}"
    };

app/views/cool_games/uploads/create.html.haml
%h1= t('uploads.result.header')
= render 'upload_results'

app/views/cool_games/uploads/index.html.haml
%h1= t('uploads.page_header')

#upload_forms
  = render :partial => 'upload_file_form'
  %hr.no-margin

  = render :partial => 'upload_url_form'
  %hr.no-margin
  
  = render :partial => 'upload_sgf_form'

- content_for :footer do
  :javascript
    initUploadPage();